// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// Get the configuration from environment variables
const firebaseConfig = {
  apiKey: "YOUR_API_KEY_HERE",
  authDomain: "YOUR_AUTH_DOMAIN_HERE",
  projectId: "YOUR_PROJECT_ID_HERE",
  storageBucket: "YOUR_STORAGE_BUCKET_HERE",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID_HERE",
  appId: "YOUR_APP_ID_HERE",
};

// A function to check if the config is valid.
// It checks if all the required environment variables are set.
function isConfigValid(config: any): boolean {
  return !Object.values(config).some(value => typeof value === 'string' && value.startsWith('YOUR_'));
}

export { firebaseConfig, isConfigValid };
