// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// Get the configuration from environment variables
const firebaseConfig = {
    apiKey: "AIzaSyCb3mTmtcOKSgmvtI7IMeGY-bkGbQ9P5Xc",
      authDomain: "kerala-rides.firebaseapp.com",
        projectId: "kerala-rides",
          storageBucket: "kerala-rides.firebasestorage.app",
            messagingSenderId: "387500806511",
              appId: "1:387500806511:web:29e665bef15c0e0b4b989a"
              };

// A function to check if the config is valid.
// It checks if all the required environment variables are set.
function isConfigValid(config: any): boolean {
  return !Object.values(config).some(value => typeof value === 'string' && value.startsWith('YOUR_'));
}

export { firebaseConfig, isConfigValid };
