// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// Get the configuration from environment variables
const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

// A function to check if the config is valid.
// It checks if all the required environment variables are set.
function isConfigValid(config: any): boolean {
  return Object.values(config).every((value) => value);
}

// If the config is not valid, we log an error to the console.
// This is helpful for debugging, as it tells the developer what's missing.
if (!isConfigValid(firebaseConfig)) {
  console.error(
    `Firebase config is not valid. Please make sure to set all the required environment variables.`
  );
}

export { firebaseConfig, isConfigValid };
